server:
  forward-headers-strategy: native
  port: 8092
spring:
  application:
    name: Hotel-Catalog-Service
  datasource:
    url: jdbc:h2:mem:hotelDB
    driver-class-name: org.h2.Driver
    username: temporary_user
    password: temporary_password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
logging:
  level:
    org:
      hibernate: warn